added some solutions to tasks
momchiltues19/UP-2021_2022 pull request #42
Opened 2021-10-25 11:23 UTC by ilievkaloyan

Ще може ли насоки за последните две задачи?

2021-10-27 17:10 UTC, stefan50 requested changes
За задача 5 помисли как да приема дата. Може да са три числа - ден, месец, година. Има няколко въпроса, които да се запиташ - колко дни има всеки месец, дали е високосна година, дали следващия ден не е в следващия месец или година, от кой до кой ден е всеки сезон.

За 6-та - тя е приложение на тази с окръжностите, но в третото пространство, което има една координата отгоре.

2021-10-27 17:10 UTC, stefan50 commented on week02/tasks/Kaloyan Iliev/task03.cpp
> +    double a, b, c, X1, X2;
Лошо именуване!

2021-10-27 17:10 UTC, stefan50 commented on week02/tasks/Kaloyan Iliev/task03.cpp
> +using std::cin;
Защо така?

2021-10-27 17:10 UTC, stefan50 commented on week02/tasks/Kaloyan Iliev/task03.cpp
> +        std::cout << (-b) / (2.0 * a) << " +/- i" << "sqrt(" << -D << ")" << '/' << 2.0 * a;
Програмата не очаквам да ми дава неопростен израз. Аз ли да смятам корен квадратен от минусово число?

2021-10-27 17:10 UTC, stefan50 commented on week02/tasks/Kaloyan Iliev/task04.cpp
> +    double first_circle_x, first_circle_y, first_circle_r;
Начални стойности трябва да има всяка променлива, за да имаме свойства детерминираност на кода

2021-10-27 17:10 UTC, stefan50 commented on week02/tasks/Kaloyan Iliev/task04.cpp
> +    if (
if?

2021-10-28 08:48 UTC, ilievkaloyan commented on week02/tasks/Kaloyan Iliev/task03.cpp
> +using std::cin;
За using std::cin и using std::cout ли става въпрос тук? 

Чувал съм, че използването на using namespace std е лоша практика, макар че за тези задачи не би трябвало да има значение. И за да не пиша "std::" пред всеки cout и cin реших да направя така. Кой вариант според вас е най-приемлив? 

Иначе го поправих на using namespace std;

2021-10-28 08:48 UTC, ilievkaloyan commented on week02/tasks/Kaloyan Iliev/task03.cpp
> +    double a, b, c, X1, X2;
Поправих променливите a,b и c да имат "coeff_" префикс, a X1 и X2 да започват с малки букви. 

Тук допуснах, че понеже става въпрос за програма решаваща квадратно уравнение и нищо друго, тези променливи имат смисъл. Все пак стандартно се използват а, b и c за означаването на коефициентите и x1, x2 за корените. 

Имам въпрос обаче, когато намесим и функции. Когато се подразбира какво прави една функция, приемливо ли е да има такова именуване на променливите? Примерно ако това беше функция, която намира корените на квадратно уравнение. Понеже самата функция няма да прави нищо друго и се подразбира, че коефициентите се наричат "a, b и c".

Идеята ми е, че понякога идентификатори от този тип "изглеждат" приемливи от контекста. Иначе, мога ли да допусна, че винаги ще се считат като лоша практика?

2021-10-28 08:48 UTC, ilievkaloyan commented on week02/tasks/Kaloyan Iliev/task03.cpp
> +        std::cout << (-b) / (2.0 * a) << " +/- i" << "sqrt(" << -D << ")" << '/' << 2.0 * a;
Поправих го директно да изчислява израза.

2021-10-28 08:48 UTC, ilievkaloyan commented on week02/tasks/Kaloyan Iliev/task04.cpp
> +    double first_circle_x, first_circle_y, first_circle_r;
Тук допуснах, че е ок понеже непосредствено се инициализират чрез cin. Има ли случай, в който това да не бъде успешно? Преди да се инициализират променливите, те и не се ползват никъде. 

Иначе, ще го поправя да са с начални стойности 0.

2021-10-28 08:48 UTC, ilievkaloyan commented on week02/tasks/Kaloyan Iliev/task04.cpp
> +    if (
Тук форматирах кода за да бъде по-четим. Отворен съм за идеи как да стане по-добре.

2021-10-28 09:39 UTC, stefan50 commented on week02/tasks/Kaloyan Iliev/task03.cpp
> +    double a, b, c, X1, X2;
Еднобуквените променливи са допустими в математиката, защото там се разглеждат малко неща и специфични. В програмирането искаме променливите да са с по-описателен характер. Следователно, за да отговоря на въпроса, дори и да е за уравнение, гледайте да пишете по-големи имена

2021-10-28 09:41 UTC, stefan50 commented on week02/tasks/Kaloyan Iliev/task03.cpp
> +using std::cin;
Аз само питам, да знам дали го разбираш. И това става, но най-предпочитаме просто да изписвате пълните наименувания

2021-10-28 09:43 UTC, stefan50 commented on week02/tasks/Kaloyan Iliev/task04.cpp
> +    double first_circle_x, first_circle_y, first_circle_r;
Няма случай, но това, което е важно, е да знаем във всеки момент стойност на променлива. Поради тази причина отсега ви караме да свиквате с идеята

2021-10-28 09:44 UTC, stefan50 commented on week02/tasks/Kaloyan Iliev/task04.cpp
> +    if (
Аха, аз съм пропуснал да го видя.

2021-10-28 09:45 UTC, merged